language: php

php: 7.1

notifications:
  email: false

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --no-interaction --prefer-source
  - rm -rf vendor/orchestra/testbench-core/laravel/storage/logs/laravel*.log

script: vendor/bin/phpunit --verbose

after_failure: cat vendor/orchestra/testbench-core/laravel/storage/logs/laravel*.log